### ISSUE TITLE
Strange message ".rO0ABXA=" appearing in queues resulting in slow queue cleaning.

### ISSUE THREAD

**Issue by alexwoopl** [awslabs/amazon-sqs-java-temporary-queues-client#11]
Currently developing an application using the request-response pattern.

After redeploying an application in ECS (old instance is stopped and new instance is started) The old instances queues remains in SQS and appears to get a few (sometimes 1 sometimes up too 11) of a strange message in it that i cant make sense of (".rO0ABXA=").

Because this is in the queue the sweeper doesn't end up deleting the old queue until the 4 days retention period is up and those messages get deleted.

In development environments and production environment this creates a lot of noise in the SQS console.

Would love if either this message didn't sent into the queue is not needed or if we were able to set the message retention attribute on the temporary queues that are made (at the moment its defaulting to 4 days and if I try to set the attribute for queue creation time then the virtual queue client throws illegal argument due to only allowing two specific attributes to be set.)

**Comment by dekelpilli** [comment]
Ok, so I had a look into this. `rO0ABXA=` decodes into `ac ed 00 05 70`, which represents a Java serialised null (https://docs.oracle.com/javase/7/docs/platform/serialization/spec/protocol.html)

**Comment by robin-aws** [comment]
Thanks for bringing this to our attention! I'm not sure where the nulls are coming from, but I'd suggest we make a patch to just discard invalid messages like this with some logging. Any of the messages in the sweeping queue are transient and resent regularly anyway, so at least if and when this happens the system could recover more gracefully.

**Comment by alexwoopl** [comment]
@robin-aws  thank you for the response! 
A patch for this would be greatly appreciated :) We are wanting to start using this in production but are slightly put off by the undying 600-700 temporary queues that are left sitting there after 4 days!

**Comment by robin-aws** [comment]
I'm now actually thinking that a better general mitigation would be to automatically create a DLQ for the sweeping queue, on top of logging for any messages that couldn't be processed. I haven't tracked down the nulls yet but that seems like a good idea anyway.

**Comment by robin-aws** [comment]
I've just released 1.0.1, which adds a DLQ to help mitigate this issue and some extra null checks to help catch it earlier.

@alexwoopl, thanks for your patience on this issue. Can you try your application with 1.0.1 and update here if the null messages are still occurring?

**Comment by dekelpilli** [comment]
I've tested it and the null messages are still appearing. Whereas before they were staying there forever and accumulating hundreds of such messages, they seem to be cleaning themselves up now, which is certainly an improvement.

**Comment by robin-aws** [comment]
Great, that makes sense - the client creates a DLQ now and those messages will be moved out of the way after 5 attempts to process them. You should see them accumulate in the __RequesterClientQueues___DLQ queue now instead. 

Is the client managing to actually clean up old idle queues now? Do you see any errors in your logs? It’s interesting that the extra null checks I added didn’t catch the null messages. If there’s any chance you can debug your runtimes to catch them it would help a lot. I’ll do some more experiments myself. 

Are

**Comment by dekelpilli** [comment]
Hmm, I'm looking at what you've done and I think there might have been a misunderstanding, although I'm not across the code base of this library so I might be wrong. The `.rO0ABXA=` message is not appearing on the sweeper queue, it's appearing on the temporary queues (__RequesterClientQueues___{uuid}). These messages have the `__AmazonSQSVirtualQueuesClient.QueueName` attribute.

Despite their appearance (and disappearance), I'm not seeing any messages in the sweeper queue's DLQ. I would like to clarify that the temporary queue (the one with the UUID) in my little small-scale test does not get delete until I shut down the **requester** app (which calls `amazonSQSRequester.shutdown()` before shutting down).

I have tried to debug it, but I'm just not sure what the final point of sending is.

**Comment by robin-aws** [comment]
Aha, thanks for clarifying that! This makes a lot more sense now - I was wondering how null values were getting into the sweeper queue. :)

This sounds like your responder application code is sending those serialized nulls as responses for some reason, and then your requester code is failing to process them. I was a bit misled at first because the sweeping process uses Java serialization as well, but the actual request/response code in the library doesn't touch the actual message content, so I don't think the library could be sending those.

The good news is that the latest release (1.0.2) fixes the issue you originally pointed out (only allowing two specific attributes to be set). That means you can set the MessageRetentionPeriod on the requester client's queues to something much shorter, even if you can't track down where the nulls are coming from. You could also set a RedrivePolicy in the same way if you wanted to move those out of the way faster.

**Comment by dekelpilli** [comment]
Yeah, I saw that PR earlier, looks good. Thanks for that.

I can probably share the code for the test apps when I get to work, but it's trivially simple. The only values I sent back are stringified primitive booleans ('Boolean.toString(bool)`), so if nulls are being sent back then it's not due an application fault in this instance. Additionally, my app is adding an attribute to the response messages that the nulls don't have, so I'm pretty confident they're generated by the SDK.

It also seems to me that the requester doesn't actually consume these nulls, but rather they just appear and disappear, which is strange.

**Comment by dekelpilli** [comment]
https://github.com/dekelpilli/sqs-temp-queue-requester
https://github.com/dekelpilli/sqs-temp-queue-responder

These are the two test services I'm running to test this SDK (keys & queue urls/arn in config file not pushed to git). If you see that I'm doing anything wrong there that might cause this issue, that would also be valuable. 

[These screenshots](https://imgur.com/a/ptV31Iv) will hopefully explain what I mean.

I've added the attributes to the queue and it worked in the sense that I can see the temporary queue has those attributes. I created a separate DLQ that all of the temporary queues point to, and that queue is empty (despite the fact that I could see that null message in the screenshot, and that those messages were never consumed^). 

---

I have made a discovery that might be important:

The two services were originally each using a different IAM user (both with `sqs:*` and nothing else) and I just noticed that the sender account IDs on the two types of messages (null vs non-null) are not the same. When I changed one of the services to use the same user as the other one  the two types of messages now have the same sender account ID. This tells me that it's actually the requester, and not the responder, that's putting the nulls on. I hope this helps.

**Comment by robin-aws** [comment]
Thanks for all the great data! :)

It's by design that the temporary queue you see on SQS itself doesn't disappear until you shut down the requester app: that's the shared host queue it will use for all the individual virtual response queues it creates on a per-request basis. That queue will not be "idle" even if the request isn't sending any requests, because a background thread will continue polling it until the whole client is shut down.

I'm now wondering if the idle queue sweeping code is accidentally sending those null messages to one of the queues it's supposed to be checking for idleness. You could try turning that off (set IdleQueueSweepingPeriod to 0: https://github.com/awslabs/amazon-sqs-java-temporary-queues-client/blob/master/src/main/java/com/amazonaws/services/sqs/AmazonSQSRequesterClientBuilder.java#L81) just to see if the null messages still appear. I'll dig into that code and try to reproduce based on the above.

**Comment by robin-aws** [comment]
Okay, I'm annoyed at myself for not figuring this out sooner, but I know exactly what's going on now. :)

The idle queue sweeping process uses the `SQSScheduledExecutorService` implementation to distribute the work, and that in turn uses the request and response clients in order to implement submitting tasks and returning their results. It uses the same configuration for temporary queues, so the response values are delivered through virtual queues on the same host queue as your application. In particular, the process calls `submit(Runnable)`, which doesn't produce a result and hence returns `null`.

My suggestion is to set the `MessageRetentionPeriod` of the response queues to something much shorter than the default of 4 days, so that any of these orphaned response messages (either for the application or the sweeping process) won't block the cleanup for very long. It's always going to be possible for occasional unclean shutdowns to leave either kind of message behind.

**Comment by dekelpilli** [comment]
Ok, thanks for that, I think at this point we'll need to test this with a bigger load (on a real server), rather than making curl requests against an app running on my machine to verify whether or not the `MessageRetentionPeriod` change fixes our core issue. I'll provide updates when we know more. 

Just to clarify, though: these nulls (`.rO0ABXA=`) are an accepted consequence of intended behaviour (meaning that they will continue to appear long term)?

**Comment by robin-aws** [comment]
With the current architecture, yes, those messages will be sent as part of the sweeping process. Since you're calling shutdown() on the requester and responder clients properly, most of the time it won't matter because the host queue will be deleted anyway. It will only matter when the shutdown is unclean, in which case there could easily be other orphaned response messages left behind anyway. That's why I'm suggesting making sure either kind of message expires fairly quickly.

It might be possible to modify the sweeping task to not send those null responses (since they aren't actually used for anything at the moment), but I'm inclined not to because having a response in general allows you to detect when a full sweep is completed, and I'm hoping to add client-side metrics around that in the future. It might be possible to make it clearer where these messages are coming from, so I'll put some thought into that.

Please do let me know if any of this interferes with your load testing!

**Comment by dekelpilli** [comment]
Hey @robin-aws, with the lower MessageRetentionPeriod, the fixes from 1.0.1, and the healthier shutdown, we are now happy with the state of SQS temporary queues and will aim to use it in production. Thanks for all of your help! 

The only thing I might suggest is lowering the default MessageRetentionPeriod of the temporary (prefix+guid) queues, and/or documenting a recommendation of doing that.
