### ISSUE TITLE
Question - regarding sendMessageAndGetResponse timeout

### ISSUE THREAD

**Issue by sheldon-markk** [awslabs/amazon-sqs-java-temporary-queues-client#14]
Based on the examples the following lines waits for the response

```
Message reply = sqs.sendMessageAndGetResponse(request, MAX_TIMEOUT, TimeUnit.SECONDS);
```
If the timeout occurs and the request fails, is the message in queue deleted? if not when will it get processed again?

**Comment by robin-aws** [comment]
The client creates a virtual queue specifically to receive that one response message, and once that message is received OR the timeout occurs, it deletes the queue. So in a logical sense it does even more than just deleting the message! Deleting a virtual queue doesn't immediately do anything to the host queue, but it does mean if the response message is received later on it will be ignored, since there is no way for the client to deliver it any more. 

If your use case requires different behaviour than the simple request/response pattern, you can always use temporary queues more directly using the AmazonSQSTemporaryQueuesClientBuilder class.

Note that you can change the behaviour invoked on messages sent to deleted virtual queues (to add logging or metrics, for example) with the OrphanedMessageHandler property on the virtual queues client builder: https://github.com/awslabs/amazon-sqs-java-temporary-queues-client/blob/master/src/main/java/com/amazonaws/services/sqs/AmazonSQSVirtualQueuesClientBuilder.java#L86

**Comment by sheldon-markk** [comment]
Thanks for the detailed explanation.
